[build]
  publish = "dist"
  command = "pnpm run build"

# Redirect to Discord server
[[redirects]]
  from = "https://chat.luvnft.com"
  to = "https://discord.gg/Sp9fubxqgf"
  status = 301
  force = true
