blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.gg/Sp9fubxqgf
    about: Ask questions and discuss with other users in real time.
  - name: Questions & Discussions
    url: https://github.com/blkluv/unity/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
